### ISSUE TITLE
Output result to JSON

### ISSUE THREAD

**Issue by anuraaga** [coreruleset/go-ftw#78]
Currently, results are only printed to the screen but it would help in post-processing to have access to them in JSON. There is a [TestStats](https://github.com/fzipi/go-ftw/blob/main/runner/stats.go#L24) which could be outputed, though for my use case it would need some extension as I'd like not only the status of non-successful items as current, but all tests and include the time taken for each test. The success/failure would be useful in verification tasks, while the timing (and not the verification) would be useful to compare runs with a WAF enabled vs disabled to check its overhead with FTW's real-world test cases (WAF disabled would fail most test cases but isn't relevant for that performance test so no problem).

**Comment by theseion** [comment]
Great idea! PR welcome 😉.

**Comment by fzipi** [comment]
I have a branch that adds an output interface, with the idea of adding GitHub and other kind of outputs. So this would be a breeze I think.

**Comment by anuraaga** [comment]
Thanks @fzipi - so to confirm you'll be sending a PR (relatively soon? :P)?

**Comment by fzipi** [comment]
Hopefully, yes! I'll tag you.

**Comment by fzipi** [comment]
@anuraaga This is what I had: https://github.com/fzipi/go-ftw/pull/82. It is in a rough state yet, I reckon.

**Comment by fzipi** [comment]
One of the annoying things I want to fix also is to have errors pointing to the yaml file from the test, instead of just failing. But that's probably for another issue.

**Comment by anuraaga** [comment]
IIUC #82 correctly, it seems to allow formatting individual test cases as JSON, so like a JSON text logger. At least for me it will be more useful to have a single test report with all the information in one JSON

**Comment by fzipi** [comment]
There are various interesting combinations the we might want. For automation, JSON global output would be good. Something like:
```
{
  tests: [
    {"test1": (timings, etc.)....},
    {"test2": ....}
  ],
  stats: {
    failed: X,
    suceeded: Y,
    total: Z,
    forced....
  }
}
```
Would make sense, but then we need to see how much we need to change for this. Instead of doing immediate output, we probably want to add results somewhere and then display everything at the end.

The original idea I had was to use it in a Github Actions setting, to show where errors are ponting to the actual test is a different idea, more focused on test to test output.

Let me do a second review, but maybe we do it in two phases: adding the interface won't hurt, but then we need the first option here to be implemented on top of that.

**Comment by fzipi** [comment]
@anuraaga sadly I didn't had any feedback from you in this one. I hope the new output is useful for you case.
