### ISSUE TITLE
Apache Documentation: Support for Latest Testing Image

### ISSUE THREAD

**Issue by MutableLoss** [coreruleset/go-ftw#93]
Hey there! 

I just wanted to point out a few things I ran across when going through the documentation to setup my own local CRS testbed. They are all very small, but my help make it easier for others in the future.

**Ftw YAML Placement**

The logfile paths give the impression that the yaml placement is in a separate folder outside of the CRS. I later found the .ftw.yaml could be placed within the CRS folder, per the gitignore file, though I'm entirely sure if this is the most common placement. 

**Apache Logfile Path** 

Documentation shows
```
logfile: '../coreruleset/tests/logs/modsec2-apache/apache2/error.log'
```

but it seems the latest docker image (September 23rd) uses:

```
logfile: '../coreruleset/tests/logs/modsec2-apache/error.log'
# or if using CRS folder
logfile: 'tests/logs/modsec2-apache/error.log'
```

**Nginx Support**

I really don't know if there are any plans to continue Nginx support, but seems only Apache ModSec2 is supported, per the [Testing Docs: Starting the Container](https://coreruleset.org/docs/development/testing/#start-the-containers). I'm not sure if this warrants a mention or not.

> -> The supported platform is modsecurity 2 with Apache

Anyways, I know it's not much, but I hope it's helpful.

**Comment by fzipi** [comment]
@MutableLoss Just a comment about the `Nginx Support` you mentioned here: CRS supports Nginx. But, the problem is that Nginx works only with ModSecurity v3. But v3 has not implemented all the directives from v2, and has slight different behavior in some cases.

That's why CRS bases the tests on the original platform. We have plans to only use go-ftw in the future, so that we might leverage some of the new features here to bring tests support for Nginx and other platforms (e.g. Coraza).

**Comment by MutableLoss** [comment]
Thanks @fzipi! I completely misunderstood. 

What led me to believe that was the cause, was that I found that were some issues using the latest image: couldn't call tests due to missing modules (iirc), 

Since I was unable to run tests on the v3 Nginx image, I thought it was still in development. I'll take a look at the image issues, and see if I can find out why this is. Cheers!
